version: '3.7'

networks:
  nphc-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

services:
  # MySQL
  mysql:
    image: mysql:8.0.29-oracle
    container_name: nphc-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - nphc-network

  # NGINX
  nginx:
    container_name: nphc-assignment-nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nphc-network
      
  # Api 
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - ${API_PORT}:3001
    container_name: nphc-assignment-backend
    restart: unless-stopped
    tty: true
    networks:
      - nphc-network

  # Client
  client:
    stdin_open: true
    container_name: nphc-assignment-frontend
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - ${APP_PORT}:3000
    networks:
      - nphc-network